### PR TITLE
 This is committing the changes I made locally

### PR DESCRIPTION
**Pull request by Getnetgit**
I made some change on readme

### CODE REVIEW

**Review by mcbariekman — COMMENTED** [review]
checked

**Review by mcbariekman — COMMENTED** [review]
checked

**Review by mcbariekman — APPROVED** [review]
checked

**Review by Ally27 — APPROVED** [review]
Sounds good

**Review by mcbariekman — APPROVED** [review]
checked

**Review by Getnetgit — COMMENTED** [review]
You have to improve your spelling. For now I will approve it.

**Pull request merged**
